[custom.all.dependent-map]
type = "local"
path = "."
ipkg = "dependent-map.ipkg"
test = "test/dependent-map-test.ipkg"

[custom.all.dependent-map-test]
type="local"
path="test"
ipkg="dependent-map-test.ipkg"

[custom.all.dtypes]
type   = "github"
url    = "git@github.com:JankaGramofonomanka/idris-dtypes.git"
commit = "11dd08baacdf98df28aa6d034bf6ff30976f298d"
ipkg   = "dtypes.ipkg"
